// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ARM_H
#define ARM_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "Preferences.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Arm: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

public:
	Arm();
	void InitDefaultCommand();
	int ConvertRotations(int, bool);
	double CurrentArmAngle();
	std::shared_ptr<SpeedController> armLeft;
	std::shared_ptr<SpeedController> armRight;
	std::shared_ptr<Encoder> armEncoder;
	std::shared_ptr<DigitalInput> armLimit;
	std::shared_ptr<AnalogInput> armAngle;
};

#endif
