// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CHASSIS_H
#define CHASSIS_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Chassis: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities


public:
	Chassis();
	void InitDefaultCommand();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<SpeedController> chassisLeft;
	std::shared_ptr<SpeedController> chassisRight;
	std::shared_ptr<RobotDrive> robotDrive;
	std::shared_ptr<Encoder> chassisLeftEncoder;
	std::shared_ptr<Encoder> chassisRightEncoder;
	std::shared_ptr<Solenoid> leftShifter;
	std::shared_ptr<Solenoid> rightShifter;
	std::shared_ptr<Ultrasonic> chassisUltrasonic;
	std::shared_ptr<AnalogGyro> gyro;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

};

#endif
