// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<SpeedController> chassisChassisLeft;
	static std::shared_ptr<SpeedController> chassisChassisRight;
	static std::shared_ptr<RobotDrive> chassisRobotDrive;
	static std::shared_ptr<Encoder> chassisChassisLeftEncoder;
	static std::shared_ptr<Encoder> chassisChassisRightEncoder;
	static std::shared_ptr<Solenoid> chassisLeftShifter;
	static std::shared_ptr<Solenoid> chassisRightShifter;
	static std::shared_ptr<Ultrasonic> chassisChassisUltrasonic;
	static std::shared_ptr<AnalogGyro> chassisGyro;
	static std::shared_ptr<SpeedController> shooterShooterTop;
	static std::shared_ptr<SpeedController> shooterShooterBottom;
	static std::shared_ptr<Relay> shooterShooterFlashlight;
	static std::shared_ptr<SpeedController> intakeIntakeVictor;
	static std::shared_ptr<AnalogInput> armArmAngle;
	static std::shared_ptr<SpeedController> armArmLeft;
	static std::shared_ptr<SpeedController> armArmRight;
	static std::shared_ptr<Encoder> armArmEncoder;
	static std::shared_ptr<DigitalInput> armArmLimit;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
